#!/bin/bash
RED='\033[0;31m'
NC='\033[0m' # No Color
#find out if user wants to update repos

read -p "Wanna pull in recent updates?" yn

#pull down changes for all repos
if [[ $yn ==  [Yy]* ]]
  then
    cd repos
    for dir in */
    do
      cd "$dir"
      git pull origin master
      cd ..
    done
fi

read -p "Wanna run the inspector?" Yn
#run git inspecter for all repos
if [[ $Yn ==  [Yy]* ]]
  then
    read -p "Do you only want to see commits made after a specific date?" yn
    if [[ $yn == [Nn]* ]]
      then
        for dir in repos/*/
          do
            python gitinspector/gitinspector.py --grading  --format=html "$dir" > results/$(basename "$dir").html
          done
      else
        read -p "When is the earliest commit you want to view? Ex: 'yesterday', 'two weeks ago', 'June 8th, 2016'" date
        for dir in repos/*/
          do
            python gitinspector/gitinspector.py --grading  --format=html --since="$date" "$dir" > results/$(basename "$dir").html
          done
    fi

fi

read -p "Wanna open the results in the browser?" YN
#open the results in the browser
if [[ $YN ==  [Yy]* ]]
  then
    for f in results/*.html
    do
      if [ -s "$f" ]
        then
          open "$f"
          continue
      fi
      echo -e "${RED}Inspection of $f failed${NC}"
    done
fi
