#!/bin/bash

#find out if user wants to update repos
read -p "Wanna pull in recent updates?" yn

#pull down changes for all repos
if [[ $yn ==  [Yy]* ]]
  then
    cd repos
    for dir in */
    do
      cd "$dir"
      git pull origin master
      cd ..
    done
fi

#run git inspecter for all repos
for dir in repos/*/
do
  python gitinspector/gitinspector.py --grading  --format=html "$dir" > results/$(basename "$dir").html
done

#open the results in the browser
for f in results/*.html
do
  if [ -s "$f" ]
    then
      open "$f"
      continue
  fi
  echo "$f failed"
done
