#!/bin/bash
RED='\033[0;31m'
NC='\033[0m' # No Color
BOLD='\033[1;m'

#clone down gitinspector
git clone https://github.com/ejwa/gitinspector.git

#create directory for repos
mkdir repos

#create directory to store gitinspector results
mkdir results

#clone all repos listed in file into repos
if [ ! -s repo-urls.txt ]
  then
    touch repo-urls.txt
    echo -e "${RED}Please add the list of repos to inspect to ${BOLD}repo-urls.txt${NC}"
    read -p "Ready to continue?" yn
    if [[ $yn !=  [Yy]* ]]
      then
        exit
    fi
fi

cd repos
while IFS= read -r var
do
  git clone "$var"
done < ../repo-urls.txt
cd ..
